themeVolume: theme # no trailing slash
sidenav: false
enabledPrezs:
  - SpacePrez
spaceprezSparqlEndpoint: #{SPACEPREZ_SPARQL_ENDPOINT}#
spaceprezSparqlUsername: #{SPACEPREZ_SPARQL_USERNAME}#
spaceprezSparqlPassword: #{SPACEPREZ_SPARQL_PASSWORD}#
demo: true
debug: true
allowPartialResults: true
systemUri: http://geofabric.surroundaustralia.com
prezTitle: GeoFabric Prez
prezDesc: Prez instance for GeoFabric
spaceprezTitle: GeoFabric Spatial Data
spaceprezDesc: Spatial data for GeoFabric
spaceprezDataUri: http://exampledata.org
appName: geofabric
deploymentMethod: kubernetes # docker, kubernetes or ecs
storageClass: ebs-sc # for kubernetes deployment
version: 0.3.1